### ISSUE TITLE
Likely possible XSS vulnerability

### ISSUE THREAD

**Issue by hrbrmstr** [norflin321/os-pulse#1]
[XSS](https://en.wikipedia.org/wiki/Cross-site_scripting)

First: neat project!

I have your deployed version in an Arc pinned tab and tap it occasionally, especially when it looks like Inoreader isn't refreshing properly.

In the attached column screenshot, you'll see a "The" entry under Hackernews. It links to the [MDN entry for the `<dialog>` HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog). I believe your code is not escaping the scraped content properly (ref: the Developer Tools Inspect pane capture in the second image).

Granted, someone would need to be targeting you or someone they know reads your deployed version, and also send some pretty sketch code to the headlines of one of the three sources you grab feeds from, so this is not really urgent or horrible. Figured you might want to know, tho.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/509878/218308952-d8b82e2e-d1ee-4c61-ae6e-0022fac3cc36.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/509878/218309172-d844af90-84fd-4355-a5cc-4b9eb64a08fd.png">

**Comment by tonku321** [comment]
Thanks for the feedback and for bringing this issue to my attention, I think my recent commit (https://github.com/norflin321/os-pulse/commit/2c248f8382559f182059c6a560bec88870328a04) fixed it.
Also I'm glad you like the app! ^_^
